version: '3.8'

services:
  mongodb:
    image: mongo:latest  # Use the latest MongoDB image from Docker Hub
    container_name: mongodb
    ports:
      - "27017:27017"  # Expose MongoDB on the default port 27017
    volumes:
      - mongodb_data:/data/db  # Persist MongoDB data
    networks:
      - app-network

  flask-app:
    build: .  # Build the Flask app from the Dockerfile in the current directory
    container_name: flask-app
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    depends_on:
      - mongodb  # Ensure MongoDB is started before Flask app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:  # Declare a Docker volume to persist MongoDB data
